#!/usr/bin/env python

import sys
sys.path.append(".")

from api import GET, POST, PUT, DELETE
import sys
import api
from collections import deque

verbose = False


class Methods(object):
    get = GET()
    post = POST()
    put = PUT()
    delete = DELETE()

args = deque(sys.argv[1:])

method = getattr(Methods, args.popleft())
path = args.popleft()
args = {k: v for k, v in (item.split('=', 2) for item in args)}
api.verbose = True
method(path, params=args)
